spring:
    datasource:  
      logapi: 
        name: logapi
        jdbc-url: jdbc:mysql://192.168.1.201:3306/suc?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
        username: suc
        password: suc
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

