server:
  port: 9100
eureka:
  client:
    service-url:
      defaultZone: http://172.18.165.230:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
spring:
  application:
    name: sts-svc
  datasource:
    order:
      name: order
      jdbcUrl: jdbc:mysql://172.18.165.232:3306/ord?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
      username: root
      password: a3f19b71d8975ca39c212e3848826bef6bc0d96c7a21587993468dcfaa3200d4
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
    user:
      name: user
      jdbc-url: jdbc:mysql://172.18.165.232:3306/suc?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
      username: root
      password: a3f19b71d8975ca39c212e3848826bef6bc0d96c7a21587993468dcfaa3200d4
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
    account:
      name: account
      jdbc-url: jdbc:mysql://172.18.165.232:3306/afc?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
      username: root
      password: a3f19b71d8975ca39c212e3848826bef6bc0d96c7a21587993468dcfaa3200d4
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
    integral:
      name: integral
      jdbc-url: jdbc:mysql://172.18.165.232:3306/pnt?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
      username: root
      password: a3f19b71d8975ca39c212e3848826bef6bc0d96c7a21587993468dcfaa3200d4
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20


logging:
  config: classpath:config/log4j2.xml
  level:
    root: info
    rebue: trace
    com.netflix.discovery: off